# Generated by Django 4.2.3 on 2023-07-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='codechef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('total_problems', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('recently_solved', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='codeforces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('total_problems', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('recently_solved', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='leaderboard',
            fields=[
                ('rollNo', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('total_problems', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='leetcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('total_problems', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('recently_solved', models.URLField()),
            ],
        ),
    ]
